### ISSUE TITLE
Window not focused when it is already in the front

### ISSUE THREAD

**Issue by TisnKu** [adirh3/Fluent-Search#852] opened 2023-06-24 07:40 UTC
**Describe the bug**
For example, when chrome window is already at the top but does not have focus, e.g. by clicking windows taskbar, switching to chrome window through Fluent-Search will not focus the chrome window

**To Reproduce**
1. Open a chrome browser window (or other window)
2. Click on windows taskbar, so that chrome window stay in the front but does not have focus
3. Trigger Fluent-Search and search for chrome window
4. Press enter to select chrome window

**Expected behavior**
Chrome window should be focused.

**Screenshots**

**Desktop (please complete the following information):**
 - Window 10/11 Version: 22H2
 - Fluent Search Version: 0.9.92.99
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment] 2023-07-22 16:36
@TisnKu I can't reproduce this issue, does it still happen for you?
Just to be sure, you mean select the Chrome window using Process Search right?

**Comment by TisnKu** [comment] 2023-07-24 02:07
@adirh3 It does not repro anymore :D .

> Just to be sure, you mean select the Chrome window using Process Search right?

Yes, using process search.

**Comment by adirh3** [comment] 2023-07-24 06:43
Thanks for the update.
Closing, feel free to reopen if it happens again.

**Closed by adirh3** 2023-07-24 06:43 UTC
