### ISSUE TITLE
Double hotkeys no longer work after latest stable build

### ISSUE THREAD

**Issue by MrFastZombie** [adirh3/Fluent-Search#174] opened 2021-06-27 22:54 UTC
**Describe the bug**
After updating it seems that hotkeys to open the search window like ctrl + ctrl no longer work, but something using differing keys such as ctrl+space works fine.

**To Reproduce**
1. Set search window hotkey to something like ctrl + ctrl
2. Try to open it with the hotkey

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1 build 19043.1052
 - Fluent Search Version 0.9.87.1

**Comment by adirh3** [comment] 2021-06-27 23:47
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment] 2021-06-28 00:37
@MrFastZombie can you please confirm if the issue is solved?

**Comment by MrFastZombie** [comment] 2021-06-28 01:08
> @MrFastZombie can you please confirm if the issue is solved?

Yes that seems to have fixed it. Thanks for the quick response!

**Closed** 2021-06-28 01:08 UTC
Labels: High Priority, bug
