### ISSUE TITLE
Settings "Windows Show location", position not good

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#118] opened 2021-06-16 05:30 UTC
**Describe the bug**
the settings `Windows Show location` when is set to `next to current process` show the FS search bar on the top, when a dialog box is open

**To Reproduce**
1. Go to an app
2. try open a file using dialog box "open" or "save as"
3. Press ur shorcut to open FS
4. see the screenshot

**Expected behavior**
The FS bar should be close the windows dialog box, or even stuck to it

**Screenshots**
![image](https://user-images.githubusercontent.com/14847187/122162872-8fdbb180-ce74-11eb-9cdd-4e6f0e53548c.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390
 - Fluent Search Version: 0.9.85.60

**Comment by adirh3** [comment] 2021-06-23 19:07
@Metroid-Prime It's by design, it's taking into account the height of the search results that will show, if you start searching you will see that it's opened in a position that it covered the least of the file dialog while not hiding any part of FS

**Comment by adirh3** [comment] 2021-06-29 22:25
@kwanice Closing this feel free to reopen if you have any suggestion

**Closed by adirh3** 2021-06-29 22:25 UTC
Labels: Medium Priority, bug

**Comment by kwanice** [comment] 2021-06-30 06:17
@adirh3 for me, the option `next to current process` should help us to get FS search engine with open box/save as box and all similar...
But if the size of FS is too big (with the recent and pin app etc...) it cant be showed properly.
If we reduce the size of FS to be showed at the bottom of the windows, the next time i open FS, the windows for the search will be too small.

So,
the size of FS should be reduced automatically to one line, when it's for a open box dialog etc...and the result should be shown for example on the top and not on the bottom.
when we open FS on other process it should be opened as usual at the center.
`next to current process` => i think you could remove that after, or add always open FS at the center, or adapt to the box dialog.

hope u get it
