### ISSUE TITLE
Files and Fluent search indexer related issues on external storage devices.

### ISSUE THREAD

**Issue by MakeshVineeth** [adirh3/Fluent-Search#225] opened 2021-07-17 10:25 UTC
**Bug 1:** Fluent Search may fail to index the external drives. Looks like when I **manually** add Indexed Paths through Settings UI, occasionally it is not updating/reflecting the same in the JSON file located at `C:\Users\username\AppData\Roaming\Blast\IndexerData\Settings\indexer.json`

**Bug 2:** Newly inserted drives are not being added to Indexed Paths in Settings > Files automatically. After inserting new drives, we have to restart FS and click on the **Revert** button for rest of the drives to appear. This doesn't fix the **Bug 1** anyway.

![2021-07-15_2](https://user-images.githubusercontent.com/19371684/126033073-7998c777-d64b-4752-a5a3-894f33dca74f.png)

**Additional Context for Bug 2:** @adirh3 already said that FS is not indexing new drives automatically by design. In such scenarios, it can be tedious work for people who deal with a lot of external storage devices. It would be awesome to have an option to automatically index new drives just like in Everything.

**Bug 3:** Revert option is shown besides File indexer even if the default options are selected. See screenshot. **(FIXED)**

![122](https://user-images.githubusercontent.com/19371684/126033033-6df07c70-d687-4ed7-9542-9461beb67628.png)

**Bug 4:** Default file manager in Settings > Files shows **Revert** option even at default values.

![2021-07-17](https://user-images.githubusercontent.com/19371684/126033594-97faf4f4-950c-40c2-b476-2cc912390c0a.png)

**Bug 5:** File extension tags shows **Revert** at it's default options.

![image](https://user-images.githubusercontent.com/19371684/126940100-1b74023e-e6c6-447e-9429-ac3e75620490.png)

**Desktop Information:**
 - Windows 11 Version: 21H2
 - Fluent Search Version: 0.9.88.78

**Comment by Metroid-Prime** [comment] 2021-07-18 06:52
It's going to be hard to track these in 1 post. @MakeshVineeth. IMO each bug should be its own post so you can verify when each one is fixed.

**Comment by MakeshVineeth** [comment] 2021-07-18 08:15
> It's going to be hard to track these in 1 post. @MakeshVineeth. IMO each bug should be its own post so you can verify when each one is fixed.

Yeah I know. Since all bugs are somehow related to either Files Settings or File Indexer, thought of posting in a single post for now.

**Comment by adirh3** [comment] 2021-07-25 21:49
This issue has been potentially fixed in version 0.9.88.90

**Comment by MakeshVineeth** [comment] 2021-07-26 06:04
> This issue has been potentially fixed in version 0.9.88.90

Only **Bug 3** has been fixed. Still facing rest of the bugs. Also added **Bug 5** to OP.

**Comment by adirh3** [comment] 2022-02-21 12:56
@MakeshVineeth can you check if all fixed please?
Note that indexer changes indexed drives only after clicking rebuild, which is by design (also added UI indication)

**Comment by MakeshVineeth** [comment] 2022-02-21 18:04
- I've enabled `Automatically add new drives` and connected the external drive, FS doesn't seem to auto add it to Indexed paths list.
- Manually added the drives and clicked on Rebuild, then also it doesn't seem to index the files on external drive. Looks like it is related to Bug 1.

**Comment by adirh3** [comment] 2022-05-27 23:07
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by MakeshVineeth** [comment] 2022-05-28 06:18
Confirmed to be working. Closing, Thanks :)

**Closed** 2022-05-28 06:18 UTC
Labels: bug, High Priority
