### ISSUE TITLE
Can't import settings

### ISSUE THREAD

**Issue by e-t-l** [adirh3/Fluent-Search#357] opened 2021-11-09 23:54 UTC
**Describe the bug**
I exported my settings from a different version of Fluent Search, but the new version won't import them.

**To Reproduce**
1. Install the Fluent Search UWP from the Microsoft Store
2. Go to Settings, click Export
3. Uninstall FS UWP
4. Install Fluent Search from executable
5. Go to Settings, click Import
6. Select either JSON file from the files created by the Export
7. Observe that no settings have been imported

**Expected behavior**
FS's settings would conform to the exported settings

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.89.9990

**Comment by adirh3** [comment] 2021-11-26 18:04
@e-t-l I can't reproduce it, was there a specific setting that was not restored?

**Comment by adirh3** [comment] 2022-03-26 13:47
Might've been an issue with sync, should be fixed by now (can't repro)

**Closed by adirh3** 2022-03-26 13:47 UTC
Labels: bug, Medium Priority, Windows 11
