### ISSUE TITLE
on "save as" dialog box, if we look for folder, settings open

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#99] opened 2021-06-11 12:13 UTC
**Describe the bug**
on a dialog box "save as", if we open FS to search for a folder, by selecting up and down, the folder is selected, but if we pressed enter, the settings windows open

**Expected behavior**
if we press enter, the selected folder should be opened

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by kwanice** [comment] 2021-06-11 12:16
i tried now, and i cant reproduced...:/

**Comment by Nomad-0** [comment] 2021-06-11 13:00
Set it to _Low priority_ as you can't reproduce

**Comment by Metroid-Prime** [comment] 2021-06-11 20:15
@kwanice  if you can't reproduce, I suggest we close this. You can always re-open easily if needed.

**Comment by Metroid-Prime** [comment] 2021-06-12 04:45
Closing this. @kwanice please reopen if you see it again or if you disagree

**Closed by Metroid-Prime** 2021-06-12 04:45 UTC
Labels: Low Priority, bug

**Comment by kwanice** [comment] 2021-06-12 05:11
ok i tried to reproduced on the new version i cant anymore...let's see @Metroid-Prime
