### ISSUE TITLE
'name' textbox in 'add task' window do not shows `|` even click on it

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#496] opened 2022-02-12 07:10 UTC
**Describe the bug**
'name' textbox in 'add task' window do not shows `|` even click on it

**To Reproduce**
1. Go to 'tasks'
2. Click on 'add task' 
3. Click on 'Name' textbox 
4. no `|` shows up

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/93647031/153701834-c762f15a-558e-4236-b897-8038ddd08d29.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.91.14

**Additional context**

**Comment by Metroid-Prime** [comment] 2022-02-12 07:16
can't reproduce win10 LTSC 2021

![image](https://user-images.githubusercontent.com/1836362/153701369-606532b5-4480-4e23-8d48-5681133d50b2.png)

**Comment by u-Sir** [comment] 2022-02-12 07:27
> can't reproduce win10 LTSC 2021
> 
> ![image](https://user-images.githubusercontent.com/1836362/153701369-606532b5-4480-4e23-8d48-5681133d50b2.png)

sorry, i didn't try to typing since it do not shows `|` when i click on textbox . I'll edit this issuse  🤣

**Comment by adirh3** [comment] 2022-02-26 20:22
@u-Sir should be fixed on latest nightly

**Closed** 2022-02-27 01:27 UTC
Labels: bug, Medium Priority
