### ISSUE TITLE
[BUG] Firefox weird behavior only when Fluent search is launched

### ISSUE THREAD

**Issue by Elaws** [adirh3/Fluent-Search#509] opened 2022-02-26 18:49 UTC
**Describe the bug**
When Fluent search is launched, every time Firefox is restored full screen (by clicking on its taskbar icon) after having been minimized, nothing happens but an "alarm" sound. It is restored full screen only after having clicked 3 to 15 times on Firefox task's bar icon.

Closing fluent search fixes the issue.

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 21H2]
 - Fluent Search Version [e.g. 0.9.90.9999]

**Comment by adirh3** [comment] 2022-02-26 20:24
@Elaws can you please check if adding FireFox to "Ignore these processes for in-app content search" in Settings -> Processes, solves the issue?

**Comment by Elaws** [comment] 2022-02-26 20:31
Thanks for your quick reply !

I have added the setting, will keep you updated. Since the problem is intermittent, I can't confirm you now that the issue is solved.

**Comment by Elaws** [comment] 2022-02-26 20:45
The problem just reproduced. Here are my settings :

![image](https://user-images.githubusercontent.com/52013479/155858528-4afeed46-ea5a-4471-b674-2dfce1fc18cd.png)

For information, no matter if Firefox is "On" or "Off", in Fluent Search, if I type "Firefox" I will anyway get "Process qwidget invisible with Firefox | 3".

**Comment by adirh3** [comment] 2022-02-26 20:51
> The problem just reproduced. Here are my settings :
> 
> ![image](https://user-images.githubusercontent.com/52013479/155858528-4afeed46-ea5a-4471-b674-2dfce1fc18cd.png)
> 
> For information, no matter if Firefox is "On" or "Off", in Fluent Search, if I type "Firefox" I will anyway get "Process qwidget invisible with Firefox | 3".

Can you please try enabling "Gaming mode" in the system tray menu, and see if it still happens?
That will disable all FS background processing.

**Comment by Elaws** [comment] 2022-02-26 20:55
I just enabled "Gaming mode" and the problem just reproduced twice.

**Comment by adirh3** [comment] 2022-02-26 21:26
> I am not 100% certain it's caused by FS. I just noticed the problem does not reproduce as soon as I kill FS process. I also noticed some stuttering (e.g. when typing inside Firefox) also disappears when I kill FS process.

Does the stuttering happen when enabling gaming mode? That taskbar issue you mentioned is actually something that happened to me as well since Windows 11, will see if I can reliably repro that.
Fluent Search is doing background process caching for in-app search which may cause it, otherwise while enabling gaming mode it should completely stop that.

**Comment by adirh3** [comment] 2022-02-26 21:53
> I have restarted FS. Maybe I did enable gaming mode too late, while the bug already happened.
> 
> * What do I loose with gaming mode enabled ?
> * Is there a way to enable it by default, or should I trigger it each time FS starts ?

Enabling gaming mode disable hotkeys and all background processing, anything related to running apps will not update anymore.
There is no way to enable it by default, its main point is to disable FS while gaming without fully closing it.

**Comment by Elaws** [comment] 2022-02-26 22:07
Oh ok, so that's not a workaround for my issue, but rather a way to identify its cause ?

I hope we find a way to use Firefox and FS, because your app is really useful !

**Comment by adirh3** [comment] 2022-02-26 22:12
> Oh ok, so that's not a workaround for my issue, but rather a way to identify its cause ?
> 
> I hope we find a way to use Firefox and FS, because your app is really useful !

Yes, we need to find the cause as it's not expected behavior.
That being said, if it is reproducible when using Gaming Mode, I am not sure what may be causing it, as Gaming Mode completely disables background processing of FS.
Just reconfirming - does the issue happen when gaming mode is enabled and all FS windows are closed?

**Comment by Elaws** [comment] 2022-02-26 23:38
- After properly rebooting and enabling gaming mode, the issue has not happened yet.
- When FS is closed, the issue has never happened yet.

**Comment by adirh3** [comment] 2022-02-27 10:38
> * After properly rebooting and enabling gaming mode, the issue has not happened yet.
> * When FS is closed, the issue has never happened yet.

Check if the issue happens again immediately after disabling gaming mode.
Seen some mention this issue for Windows 11 (they're not using FS), but I see you're using Windows 10.

**Comment by Elaws** [comment] 2022-02-27 10:43
OK, I will tell you if the issue reproduce immediately after disabling gaming mode.

I confirm you I'm using Windows 10 and not Windows 11.

**Comment by adirh3** [comment] 2022-02-28 10:28
@Elaws just got to repro this with Edge on Windows 11 but closing FS did not solve it.
Only restarting Explorer.exe worked for me.

**Comment by Elaws** [comment] 2022-02-28 10:58
Thanks for the update.

Closing FS was not enough for me either : I had to kill FS process in file explorer. Have you tried to simply kill FS process before killing the whole explorer ?

Also, a few more observations : 

- Enabling gaming mode after the bug happened does not solve the issue.
- If gaming mode is enabled before the issue happened, issue will not happen.

**Comment by azhe403** [comment] 2022-03-25 06:21
Not only Firefox. Edge too, if not ignored in app content search.
Thanks for solution

**Comment by adirh3** [comment] 2022-03-26 13:18
> Not only Firefox. Edge too, if not ignored in app content search. Thanks for solution

You have this issue as well, and when using ignored app content search it is resolved for you?

**Comment by Rhizob** [comment] 2022-05-29 06:00
I'm still experiencing this issue. On my PC, what seems to trigger it is exiting full screen on FF from my secondary monitor (dual screen setup). 

A huge thanks to everyone involved with the project.

**Comment by adirh3** [comment] 2022-05-29 07:15
> I'm still experiencing this issue. On my PC, what seems to trigger it is exiting full screen on FF from my secondary monitor (dual screen setup).
> 
> A huge thanks to everyone involved with the project.

Hey, do you have FF in the ignored processes list? In Settings -> Processes

**Comment by Rhizob** [comment] 2022-05-29 22:49
> > I'm still experiencing this issue. On my PC, what seems to trigger it is exiting full screen on FF from my secondary monitor (dual screen setup).
> > A huge thanks to everyone involved with the project.
> 
> Hey, do you have FF in the ignored processes list? In Settings -> Processes

Hey Adir,

Yes I have it ignored. It actually just happened again but this time I was in full screen (and not attempting to exit full screen) on the secondary monitor. It hasn't happened while doing the same on the primary screen.
Currently on the latest nightly build of Fluent/Windows Insider Preview 22621.1 (ni_release).

**Comment by Rhizob** [comment] 2022-08-27 03:49
> > > I'm still experiencing this issue. On my PC, what seems to trigger it is exiting full screen on FF from my secondary monitor (dual screen setup).
> > > A huge thanks to everyone involved with the project.
> > 
> > 
> > Hey, do you have FF in the ignored processes list? In Settings -> Processes
> 
> Hey Adir,
> 
> Yes I have it ignored. It actually just happened again but this time I was in full screen (and not attempting to exit full screen) on the secondary monitor. It hasn't happened while doing the same on the primary screen. Currently on the latest nightly build of Fluent/Windows Insider Preview 22621.1 (ni_release).
> 
> edit: have been testing it more on the primary monitor and it's been happening again. So, the only thing the screens/bug occurrences have in common for me is exiting from full screen FF. Bug doesn't occur while switching to full screen - only when exiting.

Update:
Haven't experienced any of mentioned issues in at least a month now. Not sure which nightly fixed it - but it seems to have resolved on my end. Thanks for all the hard work.

**Comment by adirh3** [comment] 2022-08-27 10:35
@Rhizob glad it's resolved :)

**Closed by adirh3** 2022-08-27 10:35 UTC
Labels: bug, High Priority

**Comment by Elaws** [comment] 2022-10-08 20:10
Just reinstalled FluentSearch a few days ago : the problem still occurs (Windows 11 - Firefox).

Everytime I want to restore Firefox fullscreen, I need to click twice on its taskbar icon otherwise nothing happens but an alarm sound.

EDIT : Like @Rhizob, I have a secondary monitor. I just noticed that I've not yet been able to reproduce the problem when second monitor is unplugged... So maybe a hint for a solution.
