### ISSUE TITLE
everything indexer "when in use", is not locating all folders / files

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#327] opened 2021-10-16 15:22 UTC
everything indexer "when in use", is not locating all folders / files
#BUG

**Comment by adirh3** [comment] 2021-11-14 20:04
@mragtronx8 I can't reproduce it, will need to have more info/find anything in common between files/folders not found.

**Comment by mragtronx8** [comment] 2021-11-15 06:23
@adirh3 here is an example; folder / file located in everything, but nothing in FS

![image](https://user-images.githubusercontent.com/62798102/141732374-2fffcecb-c832-4746-aa9e-b60b2dac5a22.png)
![image](https://user-images.githubusercontent.com/62798102/141732391-73c430dd-019a-4492-8126-433e74127841.png)

**Comment by mragtronx8** [comment] 2021-11-15 06:26
@adirh3 here is an example.
Folder / file is located in everything; but fs with everything indexer is not locating it.

![image](https://user-images.githubusercontent.com/62798102/141732825-46285338-1712-4eda-88a0-68dd8f212c14.png)
![image](https://user-images.githubusercontent.com/62798102/141732853-7a845905-86b2-489f-8a85-10e0facf93c3.png)

**Comment by mragtronx8** [comment] 2021-11-15 06:29
@adirh3 here is an example with everything indexer in FS
folder/file is located in everything search, but in fs nothing

![image](https://user-images.githubusercontent.com/62798102/141733107-2a9a2511-146e-4dbe-a6f2-b3196ca164aa.png)
![image](https://user-images.githubusercontent.com/62798102/141733118-9119f8ba-1f67-4db4-84d2-dd27c2456132.png)

**Comment by adirh3** [comment] 2021-11-15 09:05
@mragtronx8 does it find anything in your E drive? Can you share all your FS files settings please

**Comment by adirh3** [comment] 2022-01-08 01:08
This issue has been potentially fixed in version 0.9.90.91

**Closed as completed** 2022-01-18 18:24 UTC
Labels: bug, Medium Priority
