### ISSUE TITLE
TAG - when add a new tag, it keeps the last tag in memory

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#143] opened 2021-06-19 08:01 UTC
**Describe the bug**
when we are using the adding tag feature with the + , if we already use the adding tag feature, the box appear for the new tag is not empty but it keep in memory the previous tag used

**To Reproduce**
1. open FS
2. make a search
3. use the + to add a tag
4. open FS again
5. make a search
6. use again the + feature to add tag

**Expected behavior**
the bow should be empty

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390
 - Fluent Search Version: 0.9.85.75

**Comment by adirh3** [comment] 2021-06-27 23:47
This issue has been potentially fixed in version 0.9.88.1

**Comment by Nomad-0** [comment] 2021-06-28 00:36
@kwanice can you please confirm if the issue is solved?

**Closed** 2021-06-28 07:54 UTC
Labels: Medium Priority, bug
