### ISSUE TITLE
Automatic Bin/Hex/Dec Conversions in search window

### ISSUE THREAD

**Issue by kypi** [adirh3/Fluent-Search#272] opened 2021-09-03 17:21 UTC
**Is your feature request related to a problem? Please describe.**
Converting Decimal to hex or binary takes several steps. I'd rather it be automatic

**Describe the solution you'd like**
When a number is input into the search bar, along with other suggestions, I'd like to see Binary, Hex, and Decimal representations of the number.

**Describe alternatives you've considered**
Although I'd prefer it in main search, I've considered that this feature could be added to the calculator.

**Additional context**
The Feature request comes from a feature within a similar tool Key Piranha:
![conversion_example](https://user-images.githubusercontent.com/5155266/132043903-dc6235c9-f85e-453a-a528-54d7b54c2ff5.png)

**Comment by adirh3** [comment] 2021-09-05 22:48
This issue has been potentially fixed in version 0.9.89.2

**Comment by Nomad-0** [comment] 2021-09-07 06:55
closing it, feel free to reopen if the issue is not fixed for you

**Closed by Nomad-0** 2021-09-07 06:55 UTC
Labels: enhancement
