### ISSUE TITLE
Application icon for light mode

### ISSUE THREAD

**Issue by NuraliMedeu** [adirh3/Fluent-Search#271] opened 2021-09-03 13:57 UTC
## Is your feature request related to a problem? Please describe.
The current application icon is hard to see against light mode taskbar and system tray because of its low contrast with those GUI elements.

## Describe the solution you'd like
A separate dark application icon that is automatically enabled if Windows is in light mode.

## Describe alternatives you've considered
I tried to find a way to modify the icon inside the program files; however, I didn't find it.

## Additional context
Example of the issue:
![image](https://user-images.githubusercontent.com/44456615/132016049-47337295-cf5b-4b4d-abab-b87f4db6cc16.png)

Windows setting according to which the application should change its icon:
![image](https://user-images.githubusercontent.com/44456615/132016999-a730ea74-796b-4035-a878-8de1e0800045.png)

**Comment by adirh3** [comment] 2021-09-03 13:58
@NuraliMedeu Thanks, the icon should change in the taskbar based on Windows theme, but I will make it change in the system tray as well.

**Comment by adirh3** [comment] 2021-09-05 22:48
This issue has been potentially fixed in version 0.9.89.2

**Comment by Nomad-0** [comment] 2021-09-07 06:54
closing it, feel free to reopen if the issue is not fixed for you

**Closed by Nomad-0** 2021-09-07 06:54 UTC
Labels: UI/UX, enhancement
