### ISSUE TITLE
Search text glitches

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#78] opened 2021-06-08 05:28 UTC
**Describe the bug**
After invoking the search bar, the text glitches in the first inputs. the text shifts up and down for a while. (confirmed by @Nomad-0)

**To Reproduce**
1. Hit Fluent Search hotkey
2. Type something and observe

**Expected behavior**
normal text input

**screenshots**
![image](https://user-images.githubusercontent.com/76395594/121142617-0158a600-c85e-11eb-9452-09043847728d.png)
![image](https://user-images.githubusercontent.com/76395594/121153109-99a75880-c867-11eb-822c-7fc611d110c5.png)

**video**
https://user-images.githubusercontent.com/85425543/121127975-3eb23900-c848-11eb-8e0f-caf0118f2404.mp4
https://discord.com/channels/740636963396124714/740636963836788818/851685708845809705

**Desktop (please complete the following information):**
 - Windows 10 Version: 20H2
 - Fluent Search Version 0.9.85.30

**Comment by Nomad-0** [comment] 2021-06-08 15:54
supposedly similar issue on #79

**Comment by Nomad-0** [comment] 2021-06-09 04:41
@Metroid-Prime should I put this to **High Priority**? It's not much of a technical problem, but it's very irritating

**Comment by Metroid-Prime** [comment] 2021-06-09 04:58
Changing to high priority based on 'annoying factor' and fact that it happens on every FS launch.

I am not able to reproduce this but it has been by others.

**Comment by adirh3** [comment] 2021-06-12 00:17
This issue has been potentially fixed in version

**Comment by adirh3** [comment] 2021-06-12 00:25
This issue has been potentially fixed in version 0.9.85.40

**Comment by Nomad-0** [comment] 2021-06-12 02:14
Closing it as the issue's been fixed. @Mr-Frankenstein please check

**Closed by Nomad-0** 2021-06-12 02:14 UTC
Labels: High Priority, UI/UX, bug
