### ISSUE TITLE
search bar only not work occasionally

### ISSUE THREAD

**Issue by ltu00** [adirh3/Fluent-Search#245] opened 2021-08-03 05:50 UTC
**Describe the bug**
search bar only not work occasionally.i reset it then it work.but for a while it show full window again.

**To Reproduce**
0. dual screens
1. set search bar only and wait a min.
2. launch FS .

**Expected behavior**
show search bar only

**Screenshots**
![image](https://user-images.githubusercontent.com/50564608/127964119-5cc3bd06-90d2-4d1c-8af3-e86d251dfc4a.png)
![image](https://user-images.githubusercontent.com/50564608/127964129-4e7708d8-1108-4cea-b780-a36fb6f38a85.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.88.96

**Additional context**

**Comment by adirh3** [comment] 2021-08-06 11:18
@Nomad-0 @MakeshVineeth Can any of you reproduce?

**Comment by MakeshVineeth** [comment] 2021-08-06 11:31
Did tried quite a bit, unable to reproduce this from my end.

**Comment by Nomad-0** [comment] 2021-08-06 13:56
I can't, it could be something related to win11

**Comment by MakeshVineeth** [comment] 2021-08-06 14:17
> I can't, it could be something related to win11

I'm on Windows 11, unable to reproduce it either.

**Comment by ltu00** [comment] 2021-08-07 02:13
> @Nomad-0 @MakeshVineeth Can any of you reproduce?
it looks happened in duall screen only.@adirh3

**Comment by adirh3** [comment] 2021-08-13 15:37
> > @Nomad-0 @MakeshVineeth Can any of you reproduce?
> 
> it looks happened in dual screens only.@adirh3

I am using dual screens, can you check if it's fixed in the latest nightly version please?

**Comment by ltu00** [comment] 2021-08-14 13:42
> > > @Nomad-0 @MakeshVineeth Can any of you reproduce?
> > 
> > 
> > it looks happened in dual screens only.@adirh3
> 
> I am using dual screens, can you check if it's fixed in the latest nightly version please?

no fixed.

**Comment by ltu00** [comment] 2021-08-14 14:20
@adirh3 

https://user-images.githubusercontent.com/50564608/129449335-b537d31a-7865-4a68-ac99-ade894121777.mp4

**Closed** 2021-09-11 01:18 UTC
Labels: bug, Medium Priority, Windows 11

**Comment by adirh3** [comment] 2021-09-11 13:32
@ltu00 was it fixed?
