### ISSUE TITLE
Bug. Issue opening folder on the Home page

### ISSUE THREAD

**Issue by christubuntu** [adirh3/Fluent-Search#249] opened 2021-08-08 16:36 UTC
**Describe the bug**
FS fails to open page on the Home page when Explorer was previously closed

**To Reproduce**
1. Open Home Page on FS
2. Open any pinned/suggested directory
3. Close File Explorer
4. Try opening the same pinned/suggested folder
5. Nothing happens

**Screenshots**

https://user-images.githubusercontent.com/55885756/128639002-4b90ff19-6420-4559-8e2a-f135f1aa1b2e.mp4

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H2]
 - Fluent Search Version [e.g. 0.9.88.97]

**Additional context**
This doesn't happen when opening those folders from FS search results. Only happens for Pinned/suggested folders

**Comment by adirh3** [comment] 2021-08-13 17:56
@christubuntu Does it still happen? I can't reproduce it

**Comment by adirh3** [comment] 2021-09-11 19:35
@christubuntu Closing it, feel free to reopen if it still happens for you.

**Closed by adirh3** 2021-09-11 19:35 UTC
Labels: bug, Medium Priority
