### ISSUE TITLE
run as admin not work in powershell block in task

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#789] opened 2023-02-08 08:35 UTC
**Describe the bug**
run as admin not work in powershell block in task

**To Reproduce**
1. create any task that contains powershell script block
2. add any cmd need run as admin, e.g.  `netsh.exe  interface ipv4 set dnsservers "WLAN" static 8.8.8.8` and check the `run as admin`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Window 11 Version: 22h2
 - Fluent Search Version: 0.9.92.75
 - Installation source: Installer

**Additional context**

**Comment by adirh3** [comment] 2023-02-25 13:16
@u-Sir the issue is that when the process runs as admin Fluent Search will not be able to read its output if it's not running as admin as well.
I will fix it and add a disclaimer that it will just open the powershell window and won't be able to interact with it afterwards

**Comment by adirh3** [comment] 2023-02-25 23:54
This issue has been potentially fixed in version 0.9.92.80                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Closed** 2023-02-26 04:46 UTC
