### ISSUE TITLE
Option for disabling "Recent" in home screen 

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#202] opened 2021-07-02 21:36 UTC
**Is your feature request related to a problem? Please describe.**
The "Recent" panel in the home screen is very useful, but can be a problem during online meeting.

**Describe the solution you'd like**
I would like to have an option to disable the "Recent" and leave the search bar only.

**Comment by adirh3** [comment] 2021-07-02 22:53
@Chance92 wouldn't that be Settings -> Appearance -> Search style -> SearchBarOnly?
Do you want only the recent to hide or pinned as well?

**Comment by Chance92** [comment] 2021-07-02 23:00
@adirh3 Yes I would like to hide Recent. I am using search bar only, but I can still see recent when invoking FS:
![image](https://user-images.githubusercontent.com/85488695/124335081-01b03c80-db91-11eb-83d6-b0c7378b71c3.png)
Is "Recent" actually part of the search bar? I thought the search bar only consists of the input box on the top.

**Comment by Nomad-0** [comment] 2021-07-03 02:45
It is temporary and will be solved once Home Screen is completely implemented, Then the **Search bar only** option will have only the search bar like before. Also, I believe the issue is the same as #175. So, closing it for now.

**Closed by Nomad-0** 2021-07-03 02:45 UTC
