### ISSUE TITLE
Crashes at random

### ISSUE THREAD

**Issue by FelicitusNeko** [adirh3/Fluent-Search#379] opened 2021-12-02 04:21 UTC
**Describe the bug**
Fluent Search will quietly crash at any given point.

**To Reproduce**
1. Run Fluent Search
2. Wait (could take a variable amount of time)

**Expected behavior**
Fluent Search is ready for use.

**Screenshots**
Fluent Search has silently crashed for some unknown reason. No log file can be found.

**Desktop (please complete the following information):**
 - Windows 11 21H2 22000.318
 - Fluent Search 0.9.89.9990

**Comment by adirh3** [comment] 2021-12-02 09:51
@FelicitusNeko Can you please check the event viewer logs?
Run -> eventvwr -> Windows Logs -> Application -> Scroll to the time when FS crashed, you should see 2 errors for either ".NET Runtime" or "Fluent Search", can you please the error messages here?

**Comment by FelicitusNeko** [comment] 2021-12-02 19:09
I've now looked for those, and only found one event that happened a month ago. The program has crashed many times much more recently than that. Here's the one event that is there:

> Category: Blast.IndexerService.Worker
> EventId: 0
> 
> Trying to find path for: C:\Program Files\WindowsApps\21814BlastApps.BlastSearch_0.9.89.0_x64__pdn8zwjh47aq4

It's listed as a warning rather than an error. It is the only event listed under FluentSearch, and also the only one listed under .NET Runtime associated to FluentSearch (any other events are related to other unrelated programs).

**Comment by adirh3** [comment] 2021-12-02 19:15
> I've now looked for those, and only found one event that happened a month ago. The program has crashed many times much more recently than that. Here's the one event that is there:
> 
> > Category: Blast.IndexerService.Worker
> > EventId: 0
> > Trying to find path for: C:\Program Files\WindowsApps\21814BlastApps.BlastSearch_0.9.89.0_x64__pdn8zwjh47aq4
> 
> It's listed as a warning rather than an error. It is the only event listed under FluentSearch, and also the only one listed under .NET Runtime associated to FluentSearch (any other events are related to other unrelated programs).

Can't see anything else? It might now show have "Fluent Search" in the title, but if the app crashed a log will be generated (this is Windows mechanism).
Also, do you have "Send crash diagnostics" enabled in Settings -> System? If so, can you please let me know the exact time FS crashed so I will check if I see any errors.

One last suggestion - I see you use the Microsoft Store version, in general I recommend using the EXE installer instead, as there are compatability issues with apps like Fluent Search when used inside the Microsoft Store (which enforce the Appx installers).

**Comment by FelicitusNeko** [comment] 2021-12-02 19:18
I do have "Send crash diagnostics" enabled. It has evidently crashed sometime in the last hour, but I couldn't tell you exactly when. I only noticed it a minute ago.

As for using the EXE version, I probably would have gone right to that one if it was available on Chocolatey. That is how I tend to keep my software up to date.

**Comment by adirh3** [comment] 2021-12-02 19:33
> I do have "Send crash diagnostics" enabled. It has evidently crashed sometime in the last hour, but I couldn't tell you exactly when. I only noticed it a minute ago.
> 
> As for using the EXE version, I probably would have gone right to that one if it was available on Chocolatey. That is how I tend to keep my software up to date.

Thanks, the last was 12 hours ago, so I guess it wouldn't be this.
So, it's either crashing but fails to send the crash log, or it's somehow exits normally or being closed by other program.

Do you mind trying the EXE/Portable versions? I suspect this is due the Appx installation. (link in website - https://fluentsearch.net)
FYI - EXE updates itself and can be installed through the Windows Package Manager.
I will also upload it to Chocolatey soon.

**Comment by FelicitusNeko** [comment] 2021-12-02 20:06
I have changed to the EXE version. I'm glad there is an option to export and import all settings, so I don't have to reconfigure everything.

**Comment by adirh3** [comment] 2021-12-02 20:09
> I have changed to the EXE version. I'm glad there is an option to export and import all settings, so I don't have to reconfigure everything.

Thanks! Please let me know if the issue persists or is fixed.

**Comment by FelicitusNeko** [comment] 2021-12-03 04:49
The crash happened again. This time, an error was captured via .NET Runtime:

> Application: FluentSearch.exe
> CoreCLR Version: 6.0.21.51515
> .NET Version: 6.0.0-rtm.21515.15
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Blast.Logics.Settings.SyncSettings.SyncSettingsNow(Window window) in D:\a\1\s\Blast.Logics\Settings\SyncSettings.cs:line 189
>    at Blast.UI.Core.SettingComponents.ActionSettingControlBuilder.<>c__DisplayClass0_0.<<CreateNewControl>g__OnButtonClicked|3>d.MoveNext() in D:\a\1\s\Blast.UI.Core\SettingComponents\ActionSettingControlBuilder.cs:line 65
> --- End of stack trace from previous location ---
>    at Blast.UI.Core.SettingComponents.ActionSettingControlBuilder.<>c__DisplayClass0_0.<<CreateNewControl>b__2>d.MoveNext() in D:\a\1\s\Blast.UI.Core\SettingComponents\ActionSettingControlBuilder.cs:line 58
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
>    at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in C:\Users\adirh\RiderProjects\Avalonia\src\Avalonia.Base\Threading\JobRunner.cs:line 37
>    at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\adirh\RiderProjects\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 278
>    at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
>    at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in C:\Users\adirh\RiderProjects\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 205
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in C:\Users\adirh\RiderProjects\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 61
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in C:\Users\adirh\RiderProjects\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 126
>    at Blast.Program.Main(String[] args) in D:\a\1\s\Blast\Program.cs:line 222

This happened at around 19:27 UTC.

**Comment by adirh3** [comment] 2021-12-03 10:02
> The crash happened again. This time, an error was captured via .NET Runtime:
> 
> > Application: FluentSearch.exe
> > CoreCLR Version: 6.0.21.51515
> > .NET Version: 6.0.0-rtm.21515.15
> > Description: The process was terminated due to an unhandled exception.
> > Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
> > at Blast.Logics.Settings.SyncSettings.SyncSettingsNow(Window window) in D:\a\1\s\Blast.Logics\Settings\SyncSettings.cs:line 189
> > at Blast.UI.Core.SettingComponents.ActionSettingControlBuilder.<>c__DisplayClass0_0.<g__OnButtonClicked|3>d.MoveNext() in D:\a\1\s\Blast.UI.Core\SettingComponents\ActionSettingControlBuilder.cs:line 65
> > --- End of stack trace from previous location ---
> > at Blast.UI.Core.SettingComponents.ActionSettingControlBuilder.<>c__DisplayClass0_0.<b__2>d.MoveNext() in D:\a\1\s\Blast.UI.Core\SettingComponents\ActionSettingControlBuilder.cs:line 58
> > --- End of stack trace from previous location ---
> > at System.Threading.Tasks.Task.<>c.b__127_0(Object state)
> > at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in C:\Users\adirh\RiderProjects\Avalonia\src\Avalonia.Base\Threading\JobRunner.cs:line 37
> > at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\adirh\RiderProjects\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 278
> > at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
> > at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in C:\Users\adirh\RiderProjects\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 205
> > at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in C:\Users\adirh\RiderProjects\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 61
> > at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in C:\Users\adirh\RiderProjects\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 126
> > at Blast.Program.Main(String[] args) in D:\a\1\s\Blast\Program.cs:line 222
> 
> This happened at around 19:27 UTC.

Thank you! This issue can happen when "Sync settings with OneDrive" is enabled, it is fixed in the latest nightly build.
I suggest for now either disabling OneDrive sync or switching to the nightly build in Settings -> System -> Release feed.
Note -  the nightly build is updated daily and is more buggy.

**Comment by FelicitusNeko** [comment] 2021-12-03 14:27
All right, I've signed out of OneDrive. I'll leave this open for now, in case there's another crash. If it remains up all day, then we might be good.

**Comment by FelicitusNeko** [comment] 2021-12-03 16:43
It crashed again. This one did not show up under FluentSearch or .NET Runtime, but I did happen to notice an Application Error entry pertaining to Fluent Search:

> Faulting application name: FluentSearch.exe, version: 0.9.89.9990, time stamp: 0x616a27d5
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc00000fd
Fault offset: 0x0000000000050163
Faulting process ID: 0x5ccc
Faulting application start time: 0x01d7e851ab2165d5
Faulting application path: C:\Program Files\Fluent Search\FluentSearch.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report ID: ed504d7d-aad2-4ce4-b22d-d6fa504263e6
Faulting package full name: 
Faulting package-relative application ID: 

This was around 14:46 UTC.

**Comment by adirh3** [comment] 2021-12-03 16:57
> It crashed again. This one did not show up under FluentSearch or .NET Runtime, but I did happen to notice an Application Error entry pertaining to Fluent Search:
> 
> > Faulting application name: FluentSearch.exe, version: 0.9.89.9990, time stamp: 0x616a27d5
> > Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
> > Exception code: 0xc00000fd
> > Fault offset: 0x0000000000050163
> > Faulting process ID: 0x5ccc
> > Faulting application start time: 0x01d7e851ab2165d5
> > Faulting application path: C:\Program Files\Fluent Search\FluentSearch.exe
> > Faulting module path: C:\Windows\System32\ucrtbase.dll
> > Report ID: ed504d7d-aad2-4ce4-b22d-d6fa504263e6
> > Faulting package full name:
> > Faulting package-relative application ID:
> 
> This was around 14:46 UTC.

Thanks, did it crash during usage? Like searching? or in the background?
Do you use a custom font in Fluent Search?

**Comment by FelicitusNeko** [comment] 2021-12-03 17:12
It crashed while idle in the background. I did not change any of the font settings.

**Comment by adirh3** [comment] 2021-12-03 17:16
> It crashed while idle in the background. I did not change any of the font settings.

Can you please try enabling "Gaming mode" in the System Tray -> Enabling gaming mode, and let it stay in idle for a while to see if it's crashing?

**Comment by FelicitusNeko** [comment] 2021-12-03 23:54
So far so good. Hasn't crashed yet. Gaming mode does seem to cut down its utility some, though.

**Comment by adirh3** [comment] 2021-12-04 01:11
> So far so good. Hasn't crashed yet. Gaming mode does seem to cut down its utility some, though.

It's not meant for normal usage, only when gaming.
But knowing it doesn't crash while this is enabled will help me find the issue.

**Comment by adirh3** [comment] 2021-12-05 20:55
@FelicitusNeko few questions -
1. Do you automatically switch your Windows theme?
2. Do you see other apps crash in the Event Viewer? interestingly the faulting DLL is `ucrtbase.dll` which I see many games online that crash due to it.
3. Are you willing to switch to nightly version or custom FS version to help me find this issue? This kind of issue (stackoverflow) can not be monitored by the app itself, that's why I can't see any error on my side.

**Comment by FelicitusNeko** [comment] 2021-12-05 22:17
1) Yes, the wallpaper cycles every 30 minutes. I have three displays, so one changes every 30 minutes, and thus every individual display will change every hour and a half.
2) I'm not seeing any other application crashes which I can't otherwise identify/explain.
3) I can switch to an unstable version, but not until tomorrow.

**Comment by adirh3** [comment] 2021-12-06 08:23
> 1. Yes, the wallpaper cycles every 30 minutes. I have three displays, so one changes every 30 minutes, and thus every individual display will change every hour and a half.
> 2. I'm not seeing any other application crashes which I can't otherwise identify/explain.
> 3. I can switch to an unstable version, but not until tomorrow.

Thanks, do you have FS to follow Windows accent color (Settings -> Appearance -> Accent color -> System color)? If so, can you try to disable it and see if that's the problem.
Also, in the latest nightly version, there is a setting called `Disable app background caching` in Settings -> Apps (Advanced), can you try enabling it, restart FS and see if it's still crashing?

**Comment by FelicitusNeko** [comment] 2021-12-07 01:24
Done. I'll report back either if/when I notice it has crashed, or sometime late tonight/tomorrow morning if it hasn't.

**Comment by FelicitusNeko** [comment] 2021-12-07 05:43
After turning off "System color" and turning on "Disable app background caching" while using the nightly build, it still crashed. Same deal:

> Faulting application name: FluentSearch.exe, version: 0.9.90.65, time stamp: 0x61735063
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc00000fd
Fault offset: 0x0000000000012815
Faulting process ID: 0x2bc
Faulting application start time: 0x01d7eb091585379f
Faulting application path: C:\Program Files\Fluent Search\FluentSearch.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report ID: a342ea60-2c99-499b-9505-4242ac85c5f4
Faulting package full name: 
Faulting package-relative application ID:

**Comment by adirh3** [comment] 2021-12-09 16:46
> After turning off "System color" and turning on "Disable app background caching" while using the nightly build, it still crashed. Same deal:
> 
> > Faulting application name: FluentSearch.exe, version: 0.9.90.65, time stamp: 0x61735063
> > Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
> > Exception code: 0xc00000fd
> > Fault offset: 0x0000000000012815
> > Faulting process ID: 0x2bc
> > Faulting application start time: 0x01d7eb091585379f
> > Faulting application path: C:\Program Files\Fluent Search\FluentSearch.exe
> > Faulting module path: C:\Windows\System32\ucrtbase.dll
> > Report ID: a342ea60-2c99-499b-9505-4242ac85c5f4
> > Faulting package full name:
> > Faulting package-relative application ID:

That's super weird, sorry but can you please double check that while enabling gaming mode it doesn't happen?
Thanks!

**Comment by FelicitusNeko** [comment] 2021-12-09 23:27
So far so good. Still running.

**Comment by adirh3** [comment] 2021-12-10 15:48
Thanks again @FelicitusNeko, can you please try disabling "Search in app content" in Settings -> Processes?
Unfortunately, since this kind of crash is not debug-able, we will have to try disabling features one by one to find the culprit.

**Comment by FelicitusNeko** [comment] 2021-12-11 04:47
Once again, so far so good. No crashes, even with gaming mode disabled. Could this be the culprit?

**Comment by adirh3** [comment] 2021-12-16 13:47
> Once again, so far so good. No crashes, even with gaming mode disabled. Could this be the culprit?

It's most likely one process causing it.
To find it, you can set it to be ignored in Settings -> Processes you can set "Ignore these processes for in-app content search", this will let us know which process is problematic.
The UI caching is being invoked when you switch **out** from the process, for example if you switch from Edge to Explorer, then Edge will begin to cache.
It would be helpful if you could check which program is causing it so I can reproduce this issue on my machine and fix it.

Thanks!

**Comment by FelicitusNeko** [comment] 2021-12-16 19:06
I'm trying to add some processes to ignore, but every time I click the + button, an new entry comes up for "msedge" and it won't allow me to select it to change it to a different process.

**Comment by adirh3** [comment] 2021-12-16 21:05
> I'm trying to add some processes to ignore, but every time I click the + button, an new entry comes up for "msedge" and it won't allow me to select it to change it to a different process.

Will check that, try using the suggestion icon next to the setting name, it will show you all running processes

**Comment by FelicitusNeko** [comment] 2021-12-23 17:14
So far, I haven't found any specific process I could exclude to prevent FS from crashing.

**Comment by adirh3** [comment] 2022-01-22 21:20
@FelicitusNeko This might've been fixed in latest nightly versions, would be good if you can confirm. 
Will be pushed to stable soon.

**Comment by FelicitusNeko** [comment] 2022-01-23 00:07
I've been running it with the processes feature fully enabled for a few hours now, and it's still up. I'll update by tomorrow morning at the latest, or earlier if it does end up crashing.

**Comment by FelicitusNeko** [comment] 2022-01-23 04:57
Nope, it's still crashing.

**Comment by azhe403** [comment] 2022-05-01 04:45
FluentSearch 0.9.91.55 at Windows 11 22610.1

![image](https://user-images.githubusercontent.com/17938038/166132505-630576fd-ec63-4f53-a7a9-fcc94048363f.png)

![image](https://user-images.githubusercontent.com/17938038/166132519-222d35e5-367f-4e59-8482-71f92558d158.png)

**Comment by Metroid-Prime** [comment] 2022-05-01 07:58
@azhe403  newest beta is b0rked.  Adir has confirmed the issue, disabled the update and will have it fixed.

**Closed** 2023-07-29 15:27 UTC
Labels: bug, High Priority, Windows 11
