### ISSUE TITLE
Windows Startup Position "Feature"

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#266] opened 2021-08-29 08:51 UTC
**FEATURE REQUEST**

![image](https://user-images.githubusercontent.com/62798102/131244522-f77986cc-9f22-4cad-9b6c-789443f091e8.png)

can a "Mouse Cursor Position" be added to the windows startup position.

This way, the search bar opens where the cursor position is located.

**Comment by adirh3** [comment] 2021-09-05 22:48
This issue has been potentially fixed in version 0.9.89.2

**Comment by Nomad-0** [comment] 2021-09-07 06:55
closing it, feel free to reopen if the issue is not fixed for you

**Closed by Nomad-0** 2021-09-07 06:55 UTC
Labels: enhancement
