### ISSUE TITLE
Last used/selected command on a search result should (at least optionally) default to first

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#437] opened 2022-01-15 07:32 UTC
So I was trying to launch an app a few times using FS and it seemed to do nothing, then I realized each time it was just copying the file to the clipboard, just because a few mins ago I must've been testing out this version's changes and had left this particular search result at that command (didn't even use it, just was scrolling up/down in right pane using keyboard), and FS just defaulted to the Copy command selection every single time I tried to launch it next:

![image](https://user-images.githubusercontent.com/5120628/149613599-08ea9846-0ebb-4229-b653-3f8a211d4b48.png)
I'd expect the first (Open) command to be selected for each result by default. I'm not sure if there's a FS setting that would let me change this behavior, but right now it isn't the best (for me).

**Comment by adirh3** [comment] 2022-01-15 17:27
@erohtar It is the default, but when you have some results already selected, FS will use the last suggestion.
You know you already selected a result because of this icon - 
![image](https://user-images.githubusercontent.com/27368554/149631496-43ba470e-4d5a-449b-8cd2-60f0404364eb.png)

This was a request of some other user, not sure whether to keep it yet as it's confusing.

**Comment by Metroid-Prime** [comment] 2022-01-15 19:27
Am I understanding this correctly?

If I choose Keypass, and select "Copy File" then move left, stop the search then search for KeePass again, it defaults to Copy File?

I don't think that's user-friendly design and should be defaulted back to the top open when search window is closed.

**Comment by erohtar** [comment] 2022-01-15 19:33
> This was a request of some other user, not sure whether to keep it yet as it's confusing.

Just like @Metroid-Prime says too, it's definitely not the most optimal. If you think keeping this way has some merit too, pls provide an option to users. Ideally it should default to go back to first (for any new FS users).

**Comment by Metroid-Prime** [comment] 2022-01-15 20:19
I don't think this should have an option.  I understand 1 or 2 users may find this use case handy but I just can't see it being useful for 99.987% of users lol 

Keep it off by default

**Comment by adirh3** [comment] 2022-01-15 23:59
This issue has been potentially fixed in version 0.9.90.99

**Comment by Metroid-Prime** [comment] 2022-01-16 01:25
@erohtar  I can confirm this is fixed in the latest beta today.  I hope you don't mind me closing.

The behavior after Adir's fix is that as long as the FS search window is kept open, it remembers the setting.  If the window is closed, it defaults back to open, which is exactly what it should do.

**Closed by Metroid-Prime** 2022-01-16 01:25 UTC

**Comment by erohtar** [comment] 2022-01-16 03:54
Just tested and it works great, thank you!
@Metroid-Prime all good mate, thanks for helping convince @adirh3

**Comment by Metroid-Prime** [comment] 2022-01-16 04:51
> Just tested and it works great, thank you! @Metroid-Prime all good mate, thanks for helping convince @adirh3

All the credit goes to @adirh3       If he didn't listen to his users and set fair limits, none of this would be possible.

**Comment by erohtar** [comment] 2022-01-16 05:34
Of course! @adirh3 has been on fire - most apps don't have these many additions in regular updates as he has been adding in nightlies!
