### ISSUE TITLE
Multiplication should be done by an x sign instead of asterisk

### ISSUE THREAD

**Issue by rsmyst** [adirh3/Fluent-Search#256] opened 2021-08-17 14:01 UTC
I find hitting x much easier for multiplication since it's the way i generally write multiplication on paper. 
It'd be cool if x did that instead of asterisk. 
currently, x does some number conversion despite not having installed the plugin.
Thanks.

**Comment by Nomad-0** [comment] 2021-08-17 14:05
Some of us prefer * as we do most things related to numbers with the Numpad. However, I understand your concern and hopefully the dev would find some workaround for that

**Comment by adirh3** [comment] 2021-09-05 22:48
This issue has been potentially fixed in version 0.9.89.2

**Comment by Nomad-0** [comment] 2021-09-07 06:54
closing it, feel free to reopen if the issue is not fixed for you

**Closed by Nomad-0** 2021-09-07 06:54 UTC
Labels: modification
